"""inital seed data

Revision ID: 726b1e4f4784
Revises: 4b5ff0ca33a8
Create Date: 2023-03-27 16:39:33.753372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726b1e4f4784'
down_revision = '4b5ff0ca33a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
